version: '3.9'

services:
  contador-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      FILE_PATH: data/${COUNTER_FILE:-counter}.json
    volumes:
      - myapp:/usr/src/app/data
    container_name: contador-express

volumes:
  myapp:
